### ISSUE TITLE
Linking Errors on linux

### ISSUE THREAD

**Issue by GeorgeNs** [kmatheussen/mammut#1]
Hi. It's very interesting to see the mammut resurrected;)!

The first building step gives this error:
/usr/include/x86_64-linux-gnu/bits/fcntl2.h:50:24: error: call to ‘__open_missing_mode’ declared with attribute error: open with O_CREAT or O_TMPFILE in second argument needs 3 arguments
    __open_missing_mode ();

Then on line 392 of linux_threads cpp file i add one more argument in the end:
internal = (void*) open (temp.getFullPathName().toUTF8(), 'a', 0600); (is this correct?)
After that the first make is ok.

Then the last step fails so:
/usr/bin/x86_64-linux-gnu-ld: ../juce_1_44/juce/bin/libjuce.a(juce_linux_Threads.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libdl.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile.linux:151: recipe for target 'mammut' failed
make: *** [mammut] Error 1

I checked for -ldl in makefile,exists or something else i am missing?
Thanks~

**Comment by GeorgeNs** [comment]
Okay. I figured out that after adding 0600 as a third argument,
then I had to configure the makefile.linux and change the -ljuce position to the beginning of the list and after that i had to add also -ldl, I hope i did correct.
Now old time classics mammut has been built and run without errors!

**Comment by kmatheussen** [comment]
Great! Do you have patch or pull request?

**Comment by GeorgeNs** [comment]
I made a pull request. Hope it will be helpful. This is my first pull request so if you notice anything wrong please let me know.thanks
