### ISSUE TITLE
How about juce.h?

### ISSUE THREAD

**Issue by GeorgeNs** [kmatheussen/mammut#5]
In file included from ApplicationStartup.cpp:31:0:
AppSettings.h:27:10: fatal error: juce.h: No such file or directory
 #include "juce.h"
          ^~~~~~~~
compilation terminated.
Makefile.files:16: recipe for target 'ApplicationStartup.o' failed
make: *** [ApplicationStartup.o] Error 1
make: *** Waiting for unfinished jobs....
tempfile.cpp:8:10: fatal error: juce.h: No such file or directory
 #include "juce.h"
          ^~~~~~~~
compilation terminated.
Makefile.files:62: recipe for target 'tempfile.o' failed
make: *** [tempfile.o] Error 1

--------------------------------------------------
So cool idea to update mammut's gui!
It would be nice if surge had also juce instead of that vstgui...btw

**Comment by kmatheussen** [comment]
Fixed.
